In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

In [2]:
argentina_file_path = './Sample Data/raw stats/Argentina-Primera Division.xlsx'
england_file_path = './Sample Data/raw stats/England-Premier League.xlsx'
france_file_path = './Sample Data/raw stats/France-Ligue 1.xlsx'


argentina = pd.read_excel(argentina_file_path, index_col='ID')
england = pd.read_excel(england_file_path, index_col='ID')
france = pd.read_excel(france_file_path, index_col='ID')

In [3]:
argentina.describe()

,Age,Market value,Matches played,Minutes played,Goals,xG,Assists,xA,Height,Weight,...,Claims per 90,Claim/punch ratio,Aerial duels per 90CV,Aerial duels won %CW,FKs per 90,DFKs per 90,DFKs on target %,Corners per 90,Penalties taken,Penalty conversion %
count,489.000000,4.890000e+02,489.000000,489.000000,489.000000,489.000000,489.000000,489.000000,489.000000,489.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,26.304703,1.067229e+06,2.229039,156.443763,0.179959,0.178998,0.118609,0.107382,162.200409,67.754601,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,5.238492,1.767124e+06,0.842454,96.815511,0.453049,0.317456,0.365300,0.201167,51.453233,22.280374,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,17.000000,0.000000e+00,1.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,22.000000,2.500000e+05,1.000000,71.000000,0.000000,0.000000,0.000000,0.000000,172.000000,68.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,25.000000,4.750000e+05,2.000000,162.000000,0.000000,0.020000,0.000000,0.000000,177.000000,73.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,30.000000,1.000000e+06,3.000000,248.000000,0.000000,0.240000,0.000000,0.140000,182.000000,78.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,42.000000,1.800000e+07,3.000000,296.000000,3.000000,1.920000,2.000000,1.210000,195.000000,95.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
england.describe()

,Age,Market value,Matches played,Minutes played,Goals,xG,Assists,xA,Height,Weight,...,Claims per 90,Claim/punch ratio,Aerial duels per 90CV,Aerial duels won %CW,FKs per 90,DFKs per 90,DFKs on target %,Corners per 90,Penalties taken,Penalty conversion %
count,416.000000,4.160000e+02,416.000000,416.000000,416.000000,416.000000,416.000000,416.000000,416.000000,416.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,26.286058,1.964279e+07,5.129808,398.370192,0.569712,0.539543,0.331731,0.308173,181.971154,75.711538,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,3.980967,2.143673e+07,2.294567,247.391797,1.287548,1.033456,0.770262,0.453293,6.768754,7.764824,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,17.000000,0.000000e+00,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,163.000000,58.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,23.000000,5.000000e+06,3.000000,178.000000,0.000000,0.007500,0.000000,0.000000,177.750000,70.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,26.000000,1.200000e+07,5.000000,389.000000,0.000000,0.170000,0.000000,0.100000,182.000000,75.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,29.000000,2.500000e+07,7.000000,657.000000,1.000000,0.560000,0.000000,0.420000,187.000000,81.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,39.000000,1.280000e+08,8.000000,784.000000,8.000000,7.280000,8.000000,2.700000,199.000000,101.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
france.describe()

,Age,Market value,Matches played,Minutes played,Goals,xG,Assists,xA,Height,Weight,...,Claims per 90,Claim/punch ratio,Aerial duels per 90CV,Aerial duels won %CW,FKs per 90,DFKs per 90,DFKs on target %,Corners per 90,Penalties taken,Penalty conversion %
count,489.000000,4.890000e+02,489.000000,489.000000,489.000000,489.000000,489.000000,489.000000,489.000000,489.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,25.057260,7.012986e+06,6.139059,420.552147,0.541922,0.545521,0.310838,0.323804,178.343558,73.364008,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,4.529592,1.304765e+07,2.874615,283.288660,1.124786,0.933821,0.708196,0.524372,22.461455,11.178251,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,16.000000,0.000000e+00,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,22.000000,1.000000e+06,4.000000,178.000000,0.000000,0.010000,0.000000,0.000000,176.000000,70.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,24.000000,3.000000e+06,7.000000,381.000000,0.000000,0.160000,0.000000,0.090000,181.000000,74.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,28.000000,8.000000e+06,9.000000,651.000000,1.000000,0.590000,0.000000,0.410000,185.000000,79.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,43.000000,1.800000e+08,10.000000,973.000000,8.000000,5.870000,5.000000,4.260000,199.000000,94.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
argentina.dropna(axis='columns', how='all', inplace=True)
argentina.describe()

,Age,Market value,Matches played,Minutes played,Goals,xG,Assists,xA,Height,Weight,...,Deep completed crosses per 90,Goals total,Goals per 90CI,Shots total.1,Shots per 90CK,Clean sheets,Save %,xG against,xG against per 90,Exits per 90
count,489.000000,4.890000e+02,489.000000,489.000000,489.000000,489.000000,489.000000,489.000000,489.000000,489.000000,...,407.000000,489.000000,31.000000,489.000000,31.000000,489.000000,489.000000,489.000000,407.000000,31.000000
mean,26.304703,1.067229e+06,2.229039,156.443763,0.179959,0.178998,0.118609,0.107382,162.200409,67.754601,...,0.428673,0.186094,1.180968,0.646217,4.091935,0.044990,4.722331,0.202474,0.097813,1.673871
std,5.238492,1.767124e+06,0.842454,96.815511,0.453049,0.317456,0.365300,0.201167,51.453233,22.280374,...,0.753337,0.868466,0.854811,2.790424,1.472371,0.260084,18.289054,0.901752,0.382101,1.189178
min,17.000000,0.000000e+00,1.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.250000,0.000000,0.000000,0.000000,0.000000,0.310000
25%,22.000000,2.500000e+05,1.000000,71.000000,0.000000,0.000000,0.000000,0.000000,172.000000,68.000000,...,0.000000,0.000000,0.545000,0.000000,3.515000,0.000000,0.000000,0.000000,0.000000,0.930000
50%,25.000000,4.750000e+05,2.000000,162.000000,0.000000,0.020000,0.000000,0.000000,177.000000,73.000000,...,0.000000,0.000000,0.940000,0.000000,3.820000,0.000000,0.000000,0.000000,0.000000,1.250000
75%,30.000000,1.000000e+06,3.000000,248.000000,0.000000,0.240000,0.000000,0.140000,182.000000,78.000000,...,0.680000,0.000000,1.685000,0.000000,4.750000,0.000000,0.000000,0.000000,0.000000,2.185000
max,42.000000,1.800000e+07,3.000000,296.000000,3.000000,1.920000,2.000000,1.210000,195.000000,95.000000,...,6.620000,8.000000,3.790000,27.000000,8.350000,2.000000,100.000000,8.930000,2.760000,6.300000

In [7]:
dfs = [argentina, england, france]
all_nan_cols = []
for df in dfs:
    for col in df.columns:
        if len(df[col]) == len(df[col][df[col].isna()]):
            all_nan_cols.append(df[col].name)
            
            
print(all_nan_cols)

['Tackles per opp.30', 'Tackle succ. %', 'Interceptions per opp.30', 'Deep completed passes acc. %', 'Deep completed crosses acc. %', 'Back passes to GK per 90', 'Punches per 90', 'Punches, %', 'Claims per 90', 'Claim/punch ratio', 'Aerial duels per 90CV', 'Aerial duels won %CW', 'FKs per 90', 'DFKs per 90', 'DFKs on target %', 'Corners per 90', 'Penalties taken', 'Penalty conversion %', 'Tackles per opp.30', 'Tackle succ. %', 'Interceptions per opp.30', 'Deep completed passes acc. %', 'Deep completed crosses acc. %', 'Back passes to GK per 90', 'Punches per 90', 'Punches, %', 'Claims per 90', 'Claim/punch ratio', 'Aerial duels per 90CV', 'Aerial duels won %CW', 'FKs per 90', 'DFKs per 90', 'DFKs on target %', 'Corners per 90', 'Penalties taken', 'Penalty conversion %']

In [8]:
from collections import Counter
Counter(all_nan_cols)

Counter({'Tackles per opp.30': 2,
         'Tackle succ. %': 2,
         'Interceptions per opp.30': 2,
         'Deep completed passes acc. %': 2,
         'Deep completed crosses acc. %': 2,
         'Back passes to GK per 90': 2,
         'Punches per 90': 2,
         'Punches, %': 2,
         'Claims per 90': 2,
         'Claim/punch ratio': 2,
         'Aerial duels per 90CV': 2,
         'Aerial duels won %CW': 2,
         'FKs per 90': 2,
         'DFKs per 90': 2,
         'DFKs on target %': 2,
         'Corners per 90': 2,
         'Penalties taken': 2,
         'Penalty conversion %': 2})

In [9]:
for df in dfs:
    df.dropna(inplace=True, how='all', axis='columns')

In [10]:
argentina.select_dtypes(include=np.number).columns

Index(['Age', 'Market value', 'Matches played', 'Minutes played', 'Goals',
       'xG', 'Assists', 'xA', 'Height', 'Weight', 'Succ. def. per 90',
       'Def duels per 90', 'Def duels won %', 'Aerial duels per 90U',
       'Aerial duels won %V', 'Tackles per 90', 'Shots blocked per 90',
       'Interceptions per 90', 'Fouls per 90', 'Yellow cards',
       'Yellow cards per 90', 'Red cards', 'Red cards per 90',
       'Succ. att. actions', 'Goals per 90AI', 'Non-penalty goals',
       'Non-penalty goals per 90', 'xG per 90', 'Head goals total',
       'Head goals per 90', 'Shots total', 'Shots per 90AP',
       'Shots on target %', 'Goal conv., %', 'Assists per 90',
       'Crosses per 90', 'Crosses, %', 'Crosses from left per 90',
       'Crosses from left, %', 'Crosses from right per 90',
       'Crosses from right, %', 'Crosses to goalie box per 90',
       'Dribbles per 90', 'Dribbles succ. %', 'Touches in box per 90',
       'Passes per 90', 'Passes acc. %', 'Fwd passes per 90',
       'Fwd passes acc. %', 'Back passes per 90', 'Back passes acc. %',
       'Lat passes per 90', 'Lat passes acc. %', 'Sh/m passes per 90',
       'Sh/m passes acc. %', 'Lng passes per 90', 'Lng passes acc. %',
       'Avg pass length, m', 'Avg lng pass length, m', 'xA per 90',
       'Second assists per 90', 'Third assists per 90', 'Smt passes per 90',
       'Smt passes acc. %', 'Key passes per 90', 'Final 3rd passes per 90',
       'Final 3rd passes acc. %', 'Passes to penalty area per 90',
       'Passes to penalty area acc. %', 'Thru passes per 90',
       'Thru passes acc. %', 'Deep completed passes per 90',
       'Deep completed crosses per 90', 'Goals total', 'Goals per 90CI',
       'Shots total.1', 'Shots per 90CK', 'Clean sheets', 'Save %',
       'xG against', 'xG against per 90', 'Exits per 90'],
      dtype='object')

In [11]:
argentina_subset = argentina.select_dtypes(include=np.number)

argentina_subset = argentina_subset[argentina_subset.columns.difference(['Age','Market Value','Minutes Played','Height','Weight'])]


argentina_subset

,Aerial duels per 90U,Aerial duels won %V,Assists,Assists per 90,"Avg lng pass length, m","Avg pass length, m",Back passes acc. %,Back passes per 90,Clean sheets,Crosses from left per 90,...,Thru passes per 90,Touches in box per 90,Yellow cards,Yellow cards per 90,xA,xA per 90,xG,xG against,xG against per 90,xG per 90
ID,,,,,,,,,,,,,,,,,,,,,
AA001,4.86,62.50,0,0.00,39.73,22.52,100.00,1.52,0,0.00,...,0.30,0.30,1,0.30,0.00,0.00,0.10,0.0,0.0,0.03
AA002,1.22,75.00,0,0.00,27.03,16.00,100.00,6.39,0,0.00,...,0.00,1.82,1,0.30,0.28,0.09,0.72,0.0,0.0,0.22
AA003,2.13,28.57,0,0.00,39.84,19.74,100.00,6.39,0,0.00,...,0.91,0.61,1,0.30,0.12,0.04,0.00,0.0,0.0,0.00
AA004,3.65,58.33,0,0.00,35.86,22.68,81.82,3.34,0,0.00,...,0.00,0.61,0,0.00,0.00,0.00,0.00,0.0,0.0,0.00
AA005,3.05,60.00,1,0.31,29.94,18.57,100.00,3.97,0,3.05,...,0.61,0.31,2,0.61,0.32,0.10,0.01,0.0,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
AA485,NaN,NaN,0,NaN,0.00,2.50,NaN,NaN,0,NaN,...,NaN,NaN,0,NaN,0.00,NaN,0.00,0.0,NaN,NaN
AA486,NaN,NaN,0,NaN,0.00,0.00,NaN,NaN,0,NaN,...,NaN,NaN,0,NaN,0.00,NaN,0.00,0.0,NaN,NaN
AA487,NaN,NaN,0,NaN,0.00,23.37,NaN,NaN,0,NaN,...,NaN,NaN,0,NaN,0.00,NaN,0.00,0.0,NaN,NaN
AA488,NaN,NaN,0,NaN,0.00,9.45,NaN,NaN,0,NaN,...,NaN,NaN,0,NaN,0.00,NaN,0.00,0.0,NaN,NaN
AA489,NaN,NaN,0,NaN,0.00,27.88,NaN,NaN,0,NaN,...,NaN,NaN,0,NaN,0.00,NaN,0.00,0.0,NaN,NaN

In [12]:
scaler = MinMaxScaler()
df_arg = pd.DataFrame(scaler.fit_transform(argentina_subset), columns=argentina_subset.columns, index=argentina_subset.index)
df_arg = df_arg * 100
df_arg.iloc[200].to_clipboard(sep=',')

In [22]:
df_arg.loc[['AA098']].head()

,Aerial duels per 90U,Aerial duels won %V,Assists,Assists per 90,"Avg lng pass length, m","Avg pass length, m",Back passes acc. %,Back passes per 90,Clean sheets,Crosses from left per 90,...,Thru passes per 90,Touches in box per 90,Yellow cards,Yellow cards per 90,xA,xA per 90,xG,xG against,xG against per 90,xG per 90
ID,,,,,,,,,,,,,,,,,,,,,
AA098,19.540906,40.0,0.0,0.0,31.503032,38.877914,92.86,21.031208,0.0,7.961783,...,17.985612,27.593361,0.0,0.0,19.008264,6.896552,38.541667,0.0,0.0,15.384615

In [21]:
argentina.loc[['AA098']]['xG per 90']

ID
AA098    0.24
Name: xG per 90, dtype: float64